SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON

CREATE TABLE [dbo].[CashShopData](
    [AccountID] [varchar](10) NOT NULL,
    [WCoinC] [int] NULL,
    [WCoinP] [int] NULL,
    [GoblinPoint] [int] NULL,
    [Ruud] [int] NOT NULL,
 CONSTRAINT [PK_TempCashShop] PRIMARY KEY CLUSTERED
(
    [AccountID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING OFF
ALTER TABLE [dbo].[CashShopData] ADD DEFAULT ((0)) FOR [Ruud]