
/****** Object:  Table [dbo].[WEBENGINE_PASSCHANGE_REQUEST]    Script Date: 29/07/2025 19:39:15 ******/
SET ANSI_NULLS OFF

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING OFF

CREATE TABLE [dbo].[WEBENGINE_PASSCHANGE_REQUEST](
	[user_id] [int] NOT NULL,
	[new_password] [varchar](200) NOT NULL,
	[auth_code] [varchar](50) NOT NULL,
	[request_date] [varchar](50) NOT NULL,
 CONSTRAINT [PK_WEBENGINE_PASSCHANGE_REQUEST] PRIMARY KEY CLUSTERED 
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


SET ANSI_PADDING OFF


