
/****** Object:  Table [dbo].[WEBENGINE_BLOCKED_IP]    Script Date: 29/07/2025 19:39:15 ******/
SET ANSI_NULLS OFF

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING OFF

CREATE TABLE [dbo].[WEBENGINE_BLOCKED_IP](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[block_ip] [varchar](50) NOT NULL,
	[block_by] [varchar](25) NOT NULL,
	[block_date] [varchar](50) NOT NULL,
 CONSTRAINT [PK_WEBENGINE_BLOCKED_IP] PRIMARY KEY CLUSTERED 
(
	[block_ip] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


SET ANSI_PADDING OFF


