
/****** Object:  Table [dbo].[WEBENGINE_REDEEMCODE_LOGS]    Script Date: 29/07/2025 19:39:15 ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING ON

CREATE TABLE [dbo].[WEBENGINE_REDEEMCODE_LOGS](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[code_id] [int] NOT NULL,
	[date_redeemed] [datetime] NOT NULL,
	[ip_address] [varchar](45) NOT NULL,
	[user_identifier] [varchar](50) NOT NULL,
 CONSTRAINT [PK_WEBENGINE_REDEEMCODE_LOGS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


SET ANSI_PADDING OFF

