
/****** Object:  Table [dbo].[WEBENGINE_ACCOUNT_COUNTRY]    Script Date: 29/07/2025 19:39:15 ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

SET ANSI_PADDING ON

CREATE TABLE [dbo].[WEBENGINE_ACCOUNT_COUNTRY](
	[account] [varchar](10) NOT NULL,
	[country] [varchar](10) NOT NULL,
	[lastchange] [datetime] NULL,
 CONSTRAINT [PK_WEBENGINE_ACCOUNT_COUNTRY] PRIMARY KEY CLUSTERED 
(
	[account] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


SET ANSI_PADDING OFF

INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'1', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'11111', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'1992JJGF', N'CO', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'2', N'CA', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'3', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'4', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'5', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'acuario17', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'admin', N'HR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'admin12', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'ADMIN123', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'ADmin-2', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'ADmin-3', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'alexxdse', N'EC', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Alezan', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'alquati97', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'alquati98', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'alquati99', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'amor', N'CO', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'amorino', N'CO', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'anelo34', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Ariel', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'artifexted', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'banda', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'banda21', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'baram', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Bati1', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Bati2', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Bati3', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'bigreto23', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'BK', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'bk123', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'bordent', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'bordentt', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Bruno7x', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'brunor24', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'cannry', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'casigol', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'catanCL', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'colossuscs', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'comel', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Config', N'HR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'consue', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'consue1', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'consue2', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Corpse', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Croacia45', N'HR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Diego2025', N'IT', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'djkibo', N'VN', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'djsilva', N'CO', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'DL', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'edramgar', N'MX', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'eilera', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'ELF', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Elrobado', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'elseser', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'enchantres', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'eto228', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'faga2790', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'faguita', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'faguita27', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'farael', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'fedulo', N'UY', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'fedulo2', N'UY', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'felchuz', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'felchuz2', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'FoxDie', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'FoxDie1', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'FoxDie2', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'gerolian', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'GmHook', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'gutes22', N'UY', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'ivanlud', N'NZ', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'ivanlud1', N'NZ', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'j0elx1t015', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'JDPeron', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'jjarno', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Joczol', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'joelxito14', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'juampild', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'julioc014', N'ES', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'julioc015', N'ES', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'kamikase', N'IT', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'kansaki', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'kansaki22', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'lanfaxd', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'lau', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'laura123', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'lauta', N'HR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'lingyaoxd', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'LOCKNA', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'lsatanas1l', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'lsatanas2l', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'lsatanas3l', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'lsatanas4l', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'lsatanas5l', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'luisbringa', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'luqiito', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'luqiito1', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'luqiito2', N'PE', NULL)

INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'lxb223', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'lxb224', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'lxb226', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'makana12', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'makana123', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'manasesxd', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'mantow', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'manuel4329', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'masterx', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'matatan', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'matidelbm', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'maxito', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'mazus', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Merwuen', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'MG', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'MILAGROS22', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'miserable', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'mon0', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'mon1', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'muvillas6', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'nachoiam', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'nawee21', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'nawee22', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'pablo', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'pablo1', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'pablo2', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Pablolpz92', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Pablolpz93', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'panceta12', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'paulitoo29', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'paulo12', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Pijaman05', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'pingorocho', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Positivo', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'PTMwe001', N'VE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'PTMwe002', N'VE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'quest', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Rage12', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'recoil', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'renzodanna', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'reydemonio', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'RF', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'rifi', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'sacox', N'CO', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'sacox0', N'CO', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'samcro', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'sansaki', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'sansaki22', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Sath4nael', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'sauron215', N'VE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'sauron216', N'VE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'sauron217', N'VE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'sauron218', N'VE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'sauron219', N'VE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'sauron220', N'VE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'seba5', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'secososa', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'seebita', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'shiro15', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'Slayer', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'SM', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'soberano23', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'sombra936', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'sombra937', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'SUMM', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'TAMBO', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'tequila28', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'terrore', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'test', N'HR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'test1', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'test2', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'test3', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'test4', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'TOKRAWS', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'TOKRAWS1', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'TOKRAWS2', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'TOKRAWS3', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'TOKRAWS4', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'tomatero30', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'tristessen', N'CL', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'trome444', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'turazza', N'BR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'UraShiki01', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'UraShiki02', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'yamil6007', N'AR', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'zabulonxd', N'PE', NULL)
INSERT [dbo].[WEBENGINE_ACCOUNT_COUNTRY] ([account], [country], [lastchange]) VALUES (N'zaysdees', N'PE', NULL)


